### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [dravek/moodle-tool_powerusers#3]
Please note - all plugins that implement an integration with an external service are required to implement the privacy api - I think in your case you can implement the null provider as your plugin doesn't pass any personal identifying information to the external api, and you don't store any personal information in the plugin itself.

**Comment by dravek** [comment]
Hi @danmarsden , thanks for your review! I fixed this issue and the other 2 in this pull request: https://github.com/dravek/moodle-tool_powerusers/pull/5/files
I hope everything is fine now! Cheers!
