### ISSUE TITLE
Missing capablity check on user creation

### ISSUE THREAD

**Issue by danmarsden** [dravek/moodle-tool_powerusers#4]
As mentioned by Tomasz in the review process, the index.php is missing a require_capability check - you could probably use something like:
require_capability('moodle/site:config', context_system::instance());

or implement your own capability so that you can give certain roles the ability to add the users.

**Comment by dravek** [comment]
Hi @danmarsden , thanks for your review! I fixed this issue and the other 2 in this pull request: https://github.com/dravek/moodle-tool_powerusers/pull/5/files
I hope everything is fine now! Cheers!
